"""분석 모듈과 카메라 할당

모듈이 어디서 도는지를 코어가 모르게 하기 위한 테이블 둘.
options 는 JSON 이다 — 코어는 그 내용을 해석하지 않고 모듈에 그대로 넘긴다.

Revision ID: 74254ab30306
Revises: 4b53f639d119
Create Date: 2026-09-08 14:33:34.176746+09:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '74254ab30306'
down_revision = '4b53f639d119'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_modules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('endpoint', sa.String(length=300), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_id', sa.String(length=64), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['analytics_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'camera_id', name='uq_module_camera')
    )
    with op.batch_alter_table('module_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_assignments_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_assignments_module_id'), ['module_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_assignments_module_id'))
        batch_op.drop_index(batch_op.f('ix_module_assignments_camera_id'))

    op.drop_table('module_assignments')
    op.drop_table('analytics_modules')
    # ### end Alembic commands ###
