"""초기 스키마 — 카메라·탐지항목·인바운드 바인딩·이벤트·녹화·MQTT 로그·설정

create_all 로는 '이미 있는 테이블에 컬럼 추가'가 반영되지 않는다. 실제로 카메라에 녹화
컬럼을 붙였을 때 운영 DB 가 기동에 실패했다. 이 시점부터 스키마 변경은 전부 마이그레이션이다.

Revision ID: 4b53f639d119
Revises: 
Create Date: 2026-09-08 14:13:06.054208+09:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '4b53f639d119'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('rtsp_port', sa.Integer(), nullable=False),
    sa.Column('rtsp_path', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_enc', sa.Text(), nullable=False),
    sa.Column('mac', sa.String(length=23), nullable=False),
    sa.Column('vendor', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('record_enabled', sa.Boolean(), nullable=False),
    sa.Column('record_retention_days', sa.Integer(), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip', 'rtsp_path', name='uq_camera_endpoint')
    )
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cameras_ip'), ['ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_cameras_mac'), ['mac'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('solutions',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('short_name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('camera_solutions',
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('solution_code', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solution_code'], ['solutions.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('camera_id', 'solution_code')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('solution_code', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('module_id', sa.String(length=64), nullable=False),
    sa.Column('binding_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('snapshot_path', sa.String(length=300), nullable=False),
    sa.Column('raw_topic', sa.String(length=300), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solution_code'], ['solutions.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_cam_ts', ['camera_id', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_code'), ['code'], unique=True)
        batch_op.create_index('ix_events_sol_ts', ['solution_code', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_solution_code'), ['solution_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_ts'), ['ts'], unique=False)

    op.create_table('inbound_bindings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('transport', sa.String(length=16), nullable=False),
    sa.Column('payload_profile', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('live_only', sa.Boolean(), nullable=False),
    sa.Column('topic_pattern', sa.String(length=300), nullable=False),
    sa.Column('payload_filter', sa.JSON(), nullable=True),
    sa.Column('camera_from', sa.String(length=16), nullable=False),
    sa.Column('camera_expr', sa.String(length=200), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('item_from', sa.String(length=16), nullable=False),
    sa.Column('item_expr', sa.String(length=200), nullable=False),
    sa.Column('solution_code', sa.String(length=16), nullable=True),
    sa.Column('state_expr', sa.String(length=200), nullable=False),
    sa.Column('state_active', sa.String(length=64), nullable=False),
    sa.Column('state_inactive', sa.String(length=64), nullable=False),
    sa.Column('confidence_expr', sa.String(length=200), nullable=False),
    sa.Column('ts_expr', sa.String(length=200), nullable=False),
    sa.Column('boxes_expr', sa.String(length=200), nullable=False),
    sa.Column('boxes_format', sa.String(length=16), nullable=False),
    sa.Column('last_matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('match_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solution_code'], ['solutions.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mqtt_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('topic', sa.String(length=400), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mqtt_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mqtt_messages_topic'), ['topic'], unique=False)
        batch_op.create_index(batch_op.f('ix_mqtt_messages_ts'), ['ts'], unique=False)

    op.create_table('event_boxes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('x1', sa.Float(), nullable=False),
    sa.Column('y1', sa.Float(), nullable=False),
    sa.Column('x2', sa.Float(), nullable=False),
    sa.Column('y2', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_boxes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_boxes_event_id'), ['event_id'], unique=False)

    op.create_table('recordings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('path', sa.String(length=400), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recordings_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recordings_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recordings_start_at'), ['start_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recordings_start_at'))
        batch_op.drop_index(batch_op.f('ix_recordings_event_id'))
        batch_op.drop_index(batch_op.f('ix_recordings_camera_id'))

    op.drop_table('recordings')
    with op.batch_alter_table('event_boxes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_boxes_event_id'))

    op.drop_table('event_boxes')
    with op.batch_alter_table('mqtt_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mqtt_messages_ts'))
        batch_op.drop_index(batch_op.f('ix_mqtt_messages_topic'))

    op.drop_table('mqtt_messages')
    op.drop_table('inbound_bindings')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_ts'))
        batch_op.drop_index(batch_op.f('ix_events_solution_code'))
        batch_op.drop_index('ix_events_sol_ts')
        batch_op.drop_index(batch_op.f('ix_events_code'))
        batch_op.drop_index(batch_op.f('ix_events_camera_id'))
        batch_op.drop_index('ix_events_cam_ts')

    op.drop_table('events')
    op.drop_table('camera_solutions')
    op.drop_table('solutions')
    op.drop_table('settings')
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cameras_mac'))
        batch_op.drop_index(batch_op.f('ix_cameras_ip'))

    op.drop_table('cameras')
    # ### end Alembic commands ###
