"""아웃바운드 대상과 outbox

outbound_deliveries 를 메모리 큐가 아니라 테이블로 둔 이유
  · 수신 측이 죽어 있어도 이벤트를 잃지 않는다
  · 서버를 재시작해도 대기분이 살아남는다
  · '왜 안 갔나' 를 어드민이 볼 수 있다 (시도 횟수·실패 사유)

Revision ID: 045f53242664
Revises: 74254ab30306
Create Date: 2026-09-08 19:40:44.094508+09:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '045f53242664'
down_revision = '74254ab30306'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbound_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('solution_codes', sa.JSON(), nullable=True),
    sa.Column('camera_ids', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('payload_template', sa.Text(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('retry_backoff_sec', sa.Float(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbound_deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('topic', sa.String(length=400), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('error', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['outbound_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbound_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbound_deliveries_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_deliveries_next_attempt_at'), ['next_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_deliveries_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_deliveries_target_id'), ['target_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbound_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbound_deliveries_target_id'))
        batch_op.drop_index(batch_op.f('ix_outbound_deliveries_status'))
        batch_op.drop_index(batch_op.f('ix_outbound_deliveries_next_attempt_at'))
        batch_op.drop_index(batch_op.f('ix_outbound_deliveries_event_id'))

    op.drop_table('outbound_deliveries')
    op.drop_table('outbound_targets')
    # ### end Alembic commands ###
